// <auto-generated />
using System;
using Demo.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20240723091715_add_price")]
    partial class add_price
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Demo.Model.Maillist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "idx_email")
                        .IsUnique();

                    b.ToTable("Maillists");
                });

            modelBuilder.Entity("Demo.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRelease")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<float?>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "idx_product_name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 7, 23, 21, 17, 15, 149, DateTimeKind.Local).AddTicks(6080),
                            Description = "Shakespeare",
                            IsRelease = true,
                            Name = "William",
                            UpdateDate = new DateTime(2024, 7, 23, 21, 17, 15, 149, DateTimeKind.Local).AddTicks(6120)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 7, 23, 21, 17, 15, 149, DateTimeKind.Local).AddTicks(6120),
                            Description = "Royal Gala",
                            IsRelease = true,
                            Name = "Apple",
                            UpdateDate = new DateTime(2024, 7, 23, 21, 17, 15, 149, DateTimeKind.Local).AddTicks(6130)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 7, 23, 21, 17, 15, 149, DateTimeKind.Local).AddTicks(6130),
                            Description = "Australian",
                            IsRelease = true,
                            Name = "Orange",
                            UpdateDate = new DateTime(2024, 7, 23, 21, 17, 15, 149, DateTimeKind.Local).AddTicks(6130)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 7, 23, 21, 17, 15, 149, DateTimeKind.Local).AddTicks(6130),
                            Description = "Philippine",
                            IsRelease = true,
                            Name = "Banana",
                            UpdateDate = new DateTime(2024, 7, 23, 21, 17, 15, 149, DateTimeKind.Local).AddTicks(6130)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
